security:
  enable_authenticator_manager: true
  providers:
    users_in_memory:
      memory:
        users:
          admin:
            password: 'my_pass'
            roles: 'ROLE_ADMIN'
          user:
            password: 'other_pass'
            roles: 'ROLE_USER'
    app_user_provider:
      entity:
        class: App\Entity\User
        property: login

  password_hashers:
    App\Entity\User: auto
    Symfony\Component\Security\Core\User\InMemoryUser: plaintext

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      stateless: true
      provider: app_user_provider
      jwt: ~
      json_login:
        check_path: /authentication_token
        username_path: login
        password_path: password
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure

  access_control:
    - { path: ^/authentication_token, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
